/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_lastprime_Main */

#ifndef _Included_net_lastprime_Main
#define _Included_net_lastprime_Main
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     net_lastprime_Main
 * Method:    start
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_net_lastprime_Main_start
  (JNIEnv *, jobject, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
